# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Weekly Lotto Buy

on:
  push:
    branches: [ "main" ]
  schedule:
    # - cron: '30 1 * * 1'  # UTC 1:30(월) > KST 10:30(월)
    - cron: '30 1 * * 2'  # UTC 1:30(화) > KST 10:30(화)
    - cron: '30 1 * * 3'  # UTC 1:30(수) > KST 10:30(수)  
  # 수동 실행
  workflow_dispatch:

jobs:
  buy:
    runs-on: ubuntu-latest       # Ubuntu 24.04
    steps:
      # 1. 코드 체크아웃
      - uses: actions/checkout@v4

      # 2. Python 3.11 설치 (캐시 X)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3-A) requirements.txt 없이 직접 패키지 설치
      - name: Install Python packages
        run: |
          pip install selenium>=4.6 requests twython pillow \
                     gspread google-api-python-client oauth2client \
                     playwright
          python -m playwright install --with-deps
      # 4. 우분투 패키지 설치
      - name: Install OS packages
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-unfonts-core fonts-unfonts-extra \
                                  google-chrome-stable
      # 5. 로또 자동 구매 스크립트 실행
      - name: Run the bot
        run: |
          if [ "$(date '+%u')" -eq 3 ]; then
            python ./buy_lotto.py ${{secrets.USER_ID}} ${{secrets.USER_PW}} "auto"
          elif [ "$(date '+%u')" -eq 2 ]; then
            python ./buy_lotto.py ${{secrets.USER_ID_2}} ${{secrets.USER_PW_2}} "auto"
          fi
